### ISSUE TITLE
Does this work with non-bootstrap themes too?

### ISSUE THREAD

**Issue by ovizii** [closemarketing/bootstrap-shortcodes-for-content#1]
I'm just asking as I have found another plugin which works but its limiting the shortcodes you can use unless you buy their PRO version.

If this plugin needs bootstrap already enable inside a theme, do you have any directions on how to manually add that to an existing theme?

**Comment by davidperezgar** [comment]
Hello, In order to reduce loads of css and javascript, it does not include bootstrap. You will need it in order to see correclty the shortcodes.
